version: "3.7"
services:
  static:
    image: hidakkathon:static
    build: ../static
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: always
  app:
    image: hidakkathon:go
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: sugori_rendez_vous
      DB_USER: hidakkathon
      DB_PASS: hidakkathon
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sugori_rendez_vous
      MYSQL_USER: hidakkathon
      MYSQL_PASSWORD: hidakkathon
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ../mysql:/docker-entrypoint-initdb.d
